expeditor:
    resource: "@ExpeditorBundle/Controller/"
    type:     annotation
    prefix:   /

expeditor:
    resource: "@expeditorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
